### PR TITLE
Updated IsBusy to handle multiple IsBusy sets

### PR DESCRIPTION
**Pull request by weitzhandler**
The update targets when there are multiple tasks running, if one finishing while the other one is still running, it should become unbusy.

### CODE REVIEW

**Comment by kdawg1406** [comment]
@weitzhandler I don't have cycles to work with pull requests.  Suggestions and ideas, always welcome on the issues tab.

Good suggestion but it has some inherent problems.  Not thread safe.  Assumes a XF app will have multiple Tasks running.  If this is the case, then we need Queued Dialogs as well.  

If a XF app needs to run multiple Tasks, then I'll need to make this thread safe and add queued dialogs as well.  I had queued dialogs in WPF for the same reason.

I'll work on this on Sunday.

Best,

Karl

**Comment by weitzhandler** [comment]
U right. It's not necessary.

**Comment by weitzhandler** [comment]
Anyway, I didn't like the idea of having an `IsBusy` flag switched on and off, because I might forget the switching, so I turned the `IsBusy` setter to `private` and included a private disposable class in the view model base, so only this can set the `IsBusy` property (since it lies on the same class), so in order to set/unset the property, a `using` statement must be initiated:

    public class ViewModelBase
    {
      public bool IsBusy { get; private set; }
      protected class BusyVm : IDisposable
      {
        protected ViewModelBase ViewModel { get; }
        public BusyVm(ViewModelBase viewModel)
        {
          ViewModel = viewModel ?? throw new ArgumentNullException(nameof(viewModel));
          viewModel.IsBusy = true;
        }

        public virtual void Dispose() =>
          ViewModel.IsBusy = false;
      }
    }

Usage:

    public class ReportsViewModel : ViewModelBase
    {
        async void Load()
        {
          using(new BusyVm(this))
            Reports = await Client.GetReportsAsync();
        }
    }

**Comment by weitzhandler** [comment]
Anyway, I didn't like the idea of having an `IsBusy` flag switched on and off, because there are many occurrences where I'm loading data or performing long runs, and I might forget the busy switching which will be hard to find, so I turned the `IsBusy` setter to `private` and included a private disposable class in the view model base, so only this can set the `IsBusy` property (since it lies on the same class), so in order to set/unset the property, a `using` statement must be initiated:

    public class ViewModelBase
    {
      public bool IsBusy { get; private set; } //INPC
      protected class BusyVm : IDisposable
      {
        protected HatzolohViewModel ViewModel { get; }
        public BusyVm(HatzolohViewModel viewModel)
        {
          ViewModel = viewModel ?? throw new ArgumentNullException(nameof(viewModel));
          ViewModel.PropertyChanged += OnPropertyChanged;
          viewModel.IsBusy = true;
        }

        void OnPropertyChanged(object sender, PropertyChangedEventArgs e)
        {
          //if IsBusy is set to false by another surrounding BusyVm
          if (e.PropertyName == nameof(IsBusy) && !ViewModel.IsBusy)
            ViewModel.IsBusy = true;
        }

        public virtual void Dispose()
        {
          ViewModel.PropertyChanged -= OnPropertyChanged;
          ViewModel.IsBusy = false;
        }
      }
    }

Usage:

    public class ReportsViewModel : ViewModelBase
    {
        async void LoadReports()
        {
          using(new BusyVm(this))
            Reports = await Client.GetReportsAsync();
        }
        async void LoadVerbs()
        {
          using(new BusyVm(this))
            Verbs = await Client.GetVerbsAsync();
        }
        async void LoadData()
        {
          using(new BusyVm(this))
          {
            LoadReports();
            LoadVerbs();
          }
        }
    }

**Comment by weitzhandler** [comment]
And actually, the problem is not about multi-threading. It's about ensuring the models states busy if a wrapped call unbusys the VM:

     async void LoadResponders()
     {
       IsBusy = true;
       Responders = await Client.GetResponders();
       IsBusy = false;
     }
  
     async void LoadRespondersAndIntersections()
     {        
       IsBusy = true; 
       await LoadResponders(); //IsBusy becomes false when returning here
       //of course we could move the IsBusy over here, but I see it as error prone.
       Intersections = await Client.LoadIntersections();
       IsBusy = false;
     }
  
So I've expanded my above solution to ensure the VM remains busy until all `BusyVm`s have been disposed:

      protected class BusyVm : IDisposable
      {
        protected HatzolohViewModel ViewModel { get; }
        public BusyVm(HatzolohViewModel viewModel)
        {
          ViewModel = viewModel ?? throw new ArgumentNullException(nameof(viewModel));
          ViewModel.PropertyChanged += OnPropertyChanged;
          viewModel.IsBusy = true;
        }

        void OnPropertyChanged(object sender, PropertyChangedEventArgs e)
        {
          //if IsBusy is set to false by another BusyVm
          if (e.PropertyName == nameof(IsBusy) && !ViewModel.IsBusy)
            ViewModel.IsBusy = true;
        }

        public virtual void Dispose()
        {
          ViewModel.PropertyChanged -= OnPropertyChanged;
          ViewModel.IsBusy = false;
        }
      }

**Pull request closed without merging**
